#! /usr/bin/env php
<?php

use Symfony\Component\Console\Application;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Symfony\Component\Console\Input\InputArgument;

require 'vendor/autoload.php';

/*
 *instance new App object
*/
$app = new Application('Laracast Demo','1.0');

$app->register('sayHelloTo')
    ->setDescription('Offer a greeting to a given person.')
    ->addArgument('name',InputArgument::OPTIONAL,'Your Name')
    ->setCode(function(InputInterface $input, OutputInterface $output)
    {
        $messages = 'Hello, ' . $input->getArgument('name');
        $output->writeln("<info>{$messages}</info>");
    });

//run the application
$app->run();
